<template>
  <PageHeader title="Nhà xuất bản" subtitle="Quản lý thông tin nhà xuất bản trong thư viện" breadcrumb="Nhà xuất bản">
    <div class="btn-row"><button class="primary-btn" @click="openCreate"><v-icon icon="mdi-plus" /> Thêm NXB</button><button class="ghost-btn" @click="exportCsv"><v-icon icon="mdi-download" /> Xuất CSV</button></div>
  </PageHeader>
  <div v-if="error" class="card card-pad" style="margin-bottom:16px;color:#ef4444">{{ error }}</div>
  <div v-if="success" class="card card-pad" style="margin-bottom:16px;color:#16a34a">{{ success }}</div>
  <div class="grid grid-4" style="margin-bottom:18px"><StatCard label="Tổng NXB" :value="publishers.length" icon="mdi-office-building-outline" /><StatCard label="Đang hoạt động" :value="activeCount" icon="mdi-check-circle-outline" color="#16a34a" bg="#ecfdf5" /><StatCard label="Ngưng hợp tác" :value="inactiveCount" icon="mdi-handshake-outline" color="#f97316" bg="#fff7ed" /><StatCard label="Dữ liệu" value="API" icon="mdi-cloud-check-outline" color="#7c3aed" bg="#f5f3ff" /></div>
  <div class="two-column"><div class="card"><div class="filter-bar" style="grid-template-columns:2fr 1fr auto auto"><input class="input" placeholder="Tìm theo tên nhà xuất bản..." v-model="q" /><select class="select" v-model="status"><option value="">Tất cả trạng thái</option><option value="Hoạt động">Hoạt động</option><option value="Ngưng sử dụng">Ngưng hợp tác</option></select><button class="primary-btn" @click="loadData">Tải lại</button><button class="ghost-btn" @click="reset">Đặt lại</button></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Tên NXB</th><th>Quốc gia</th><th>Email</th><th>Điện thoại</th><th>Trạng thái</th><th>Cập nhật</th><th>Thao tác</th></tr></thead><tbody><tr v-for="(item,i) in filtered" :key="item.id"><td>{{ i+1 }}</td><td><b>{{ item.name }}</b></td><td>{{ item.country }}</td><td>{{ item.email }}</td><td>{{ item.phone }}</td><td><StatusBadge :text="item.status" /></td><td>{{ item.updatedAt }}</td><td><button class="action-btn" @click="openEdit(item)"><v-icon icon="mdi-pencil-outline" /></button><button class="action-btn danger" @click="removeItem(item)"><v-icon icon="mdi-trash-can-outline" /></button></td></tr><tr v-if="!loading && filtered.length===0"><td colspan="8" class="empty-state">Không có nhà xuất bản phù hợp.</td></tr></tbody></table></div></div><SideStats title="Quản lý NXB" :total="String(publishers.length)" :items="['Thêm/sửa nhà xuất bản qua Catalog API','Ngưng hợp tác thay vì xóa cứng','Dùng cho danh mục sách']" /></div>
  <div v-if="showForm" class="modal-backdrop"><div class="modal-card"><h3 class="section-title">{{ editingId ? 'Cập nhật nhà xuất bản' : 'Thêm nhà xuất bản' }}</h3><div class="form-grid"><div class="field"><label>Tên NXB *</label><input class="input" v-model="form.name" /></div><div class="field"><label>Quốc gia</label><input class="input" v-model="form.country" /></div><div class="field"><label>Email</label><input class="input" v-model="form.email" /></div><div class="field"><label>Điện thoại</label><input class="input" v-model="form.phone" /></div><div class="field" style="grid-column:1/-1"><label>Địa chỉ</label><textarea v-model="form.address" /></div></div><div class="form-actions"><button class="ghost-btn" @click="showForm=false">Hủy</button><button class="primary-btn" :disabled="saving" @click="saveItem">{{ saving ? 'Đang lưu...' : 'Lưu' }}</button></div></div></div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'; import PageHeader from '../components/PageHeader.vue'; import StatCard from '../components/StatCard.vue'; import StatusBadge from '../components/StatusBadge.vue'; import SideStats from '../components/SideStats.vue'; import { catalogApi, getErrorMessage } from '../services/api'; import { mapLookup } from '../services/adapters'
const publishers=ref([]), q=ref(''), status=ref(''), loading=ref(false), saving=ref(false), error=ref(''), success=ref(''), showForm=ref(false), editingId=ref(null); const form=reactive({name:'',country:'',address:'',email:'',phone:''})
const filtered=computed(()=>publishers.value.filter(x=>(!q.value||x.name.toLowerCase().includes(q.value.toLowerCase()))&&(!status.value||x.status===status.value))); const activeCount=computed(()=>publishers.value.filter(x=>x.status==='Hoạt động').length); const inactiveCount=computed(()=>publishers.value.filter(x=>x.status!=='Hoạt động').length)
onMounted(loadData); async function loadData(){loading.value=true;error.value='';try{const{data}=await catalogApi.publishers();publishers.value=data.map(x=>mapLookup(x,'publisher'))}catch(e){error.value=getErrorMessage(e,'Không tải được nhà xuất bản.')}finally{loading.value=false}} function reset(){q.value='';status.value=''} function openCreate(){editingId.value=null;Object.assign(form,{name:'',country:'',address:'',email:'',phone:''});showForm.value=true} function openEdit(item){editingId.value=item.id;Object.assign(form,{name:item.name,country:item.country,address:item.address,email:item.email,phone:item.phone});showForm.value=true} async function saveItem(){saving.value=true;error.value='';success.value='';try{if(editingId.value){await catalogApi.updatePublisher(editingId.value,{...form});success.value='Cập nhật NXB thành công.'}else{await catalogApi.createPublisher({...form});success.value='Thêm NXB thành công.'}showForm.value=false;await loadData()}catch(e){error.value=getErrorMessage(e,'Lưu NXB thất bại.')}finally{saving.value=false}} async function removeItem(item){if(!confirm(`Ngưng hợp tác NXB ${item.name}?`))return;try{await catalogApi.deletePublisher(item.id);success.value='Đã ngưng hợp tác NXB.';await loadData()}catch(e){error.value=getErrorMessage(e,'Không thể ngưng hợp tác NXB.')}} function exportCsv(){const rows=[['Tên','Quốc gia','Email','Điện thoại','Trạng thái'],...filtered.value.map(x=>[x.name,x.country,x.email,x.phone,x.status])];const csv=rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='publishers.csv';a.click();URL.revokeObjectURL(url)}
</script>
