<template><div>
  <div class="page-head"><div><h1>Tra cứu sách</h1><p>Tìm kiếm sách theo tên, ISBN, tác giả, thể loại, nhà xuất bản và tình trạng khả dụng</p></div></div>
  <div v-if="error" class="alert error">{{error}}</div>
  <div class="grid grid-4"><div class="card stat"><div class="stat-icon blue"><i class="mdi mdi-book-open"></i></div><div><div class="stat-label">Tổng sách</div><div class="stat-value">{{books.length}}</div></div></div><div class="card stat"><div class="stat-icon green"><i class="mdi mdi-book-check"></i></div><div><div class="stat-label">Có thể mượn</div><div class="stat-value">{{availableBooks}}</div></div></div><div class="card stat"><div class="stat-icon orange"><i class="mdi mdi-book-clock"></i></div><div><div class="stat-label">Đang mượn</div><div class="stat-value">{{borrowedCopies}}</div></div></div><div class="card stat"><div class="stat-icon purple"><i class="mdi mdi-cellphone-link"></i></div><div><div class="stat-label">Bản sao</div><div class="stat-value">{{copies.length}}</div></div></div></div>
  <div class="split" style="margin-top:16px">
    <section class="card pad"><div class="toolbar"><div class="field"><label>Từ khóa</label><input class="input" v-model="params.keyword" @keyup.enter="load" placeholder="Tên sách, ISBN, tác giả"></div><div class="field"><label>Năm XB</label><input class="input" v-model="params.year" placeholder="2024"></div><div class="field"><label>Tình trạng</label><select class="select" v-model="availabilityFilter"><option value="">Tất cả</option><option value="available">Có thể mượn</option><option value="empty">Hết bản sẵn sàng</option></select></div><button class="btn primary" @click="load">Tìm kiếm</button><button class="btn" @click="reset">Đặt lại</button></div>
      <div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Ảnh</th><th>Tên sách</th><th>Tác giả</th><th>Năm</th><th>ISBN</th><th>Sẵn có</th><th>Thao tác</th></tr></thead><tbody><tr v-for="b in filteredBooks" :key="b.id"><td><div class="avatar" style="border-radius:10px"><i class="mdi mdi-book-open-page-variant"></i></div></td><td><b>{{b.title}}</b><br><small>{{b.categoryName||'-'}}</small></td><td>{{b.authorName||'-'}}</td><td>{{b.publishYear||b.publicationYear||'-'}}</td><td>{{b.isbn||b.ISBN}}</td><td><span class="badge" :class="availableCount(b)>0?'green':'red'">{{availableCount(b)}} bản</span></td><td><button class="mini" @click="selectBook(b)">Xem</button></td></tr><tr v-if="!filteredBooks.length"><td colspan="7" class="empty">Không có sách phù hợp.</td></tr></tbody></table></div></section>
    <section class="card pad"><h2 class="section-title">Thông tin sách</h2><div v-if="selected"><h3>{{selected.title}}</h3><p class="sub-title">{{selected.description||'Chưa có mô tả.'}}</p><div class="info-list"><div class="info-row"><span>ISBN</span><b>{{selected.isbn||selected.ISBN}}</b></div><div class="info-row"><span>Tác giả</span><b>{{selected.authorName||'-'}}</b></div><div class="info-row"><span>Thể loại</span><b>{{selected.categoryName||'-'}}</b></div><div class="info-row"><span>NXB</span><b>{{selected.publisherName||'-'}}</b></div><div class="info-row"><span>Số bản sao</span><b>{{bookCopies.length}}</b></div></div><h3>Vị trí & bản sao</h3><table><thead><tr><th>Mã</th><th>Vị trí</th><th>Trạng thái</th></tr></thead><tbody><tr v-for="c in bookCopies" :key="c.id"><td>{{c.copyCode}}</td><td>{{c.shelfLocation}}</td><td>{{enumText(c.borrowStatus,statusMaps.copy)}}</td></tr><tr v-if="!bookCopies.length"><td colspan="3" class="empty">Chưa có bản sao.</td></tr></tbody></table></div><div v-else class="empty">Chọn sách để xem chi tiết.</div></section>
  </div>
</div></template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {useRoute} from 'vue-router'
import {catalogApi,dataOf,getErrorMessage,enumText,statusMaps} from '../services/api'
const route=useRoute(); const books=ref([]), copies=ref([]), selected=ref(null), bookCopies=ref([]), error=ref(''), availabilityFilter=ref('')
const params=reactive({keyword:route.query.q||'',year:''})
const availableBooks=computed(()=>books.value.filter(b=>availableCount(b)>0).length)
const borrowedCopies=computed(()=>copies.value.filter(c=>Number(c.borrowStatus)===2||c.borrowStatus==='Borrowed').length)
function availableCount(b){return Number(b.availableCopies ?? b.availableCount ?? copies.value.filter(c=>c.bookId===b.id && (Number(c.borrowStatus)===1 || c.borrowStatus==='Available')).length)}
const filteredBooks=computed(()=>books.value.filter(b=>availabilityFilter.value==='available'?availableCount(b)>0:availabilityFilter.value==='empty'?availableCount(b)===0:true))
async function load(){error.value='';try{const [bs,cs]=await Promise.all([catalogApi.searchBooks(params),catalogApi.copies()]);books.value=dataOf(bs);copies.value=dataOf(cs)}catch(e){error.value=getErrorMessage(e,'Không tải được sách.')}}
function reset(){params.keyword='';params.year='';availabilityFilter.value='';load()} async function selectBook(b){selected.value=b; try{bookCopies.value=dataOf(await catalogApi.bookCopies(b.id))}catch{bookCopies.value=copies.value.filter(c=>c.bookId===b.id)}}
onMounted(load)
</script>
