<template><div><div class="page-head"><div><h1>Hồ sơ cá nhân</h1><p>Xem và cập nhật thông tin tài khoản thủ thư đang đăng nhập</p></div></div><div v-if="error" class="alert error">{{error}}</div><div v-if="success" class="alert success">{{success}}</div><div class="split"><section class="card pad"><div style="text-align:center"><div class="avatar" style="width:110px;height:110px;margin:0 auto 18px;font-size:34px">{{initials}}</div><h2>{{profile.fullName||'Thủ thư'}}</h2><span class="badge green">Đang hoạt động</span></div><div class="info-list" style="margin-top:24px"><div class="info-row"><span>Email</span><b>{{profile.email||'-'}}</b></div><div class="info-row"><span>Tên đăng nhập</span><b>{{profile.username||'-'}}</b></div><div class="info-row"><span>Số điện thoại</span><b>{{profile.phone||'-'}}</b></div><div class="info-row"><span>Vai trò</span><b>{{profile.role||profile.roleName||'Thủ thư'}}</b></div></div></section><section class="card pad"><h2 class="section-title">Thông tin cá nhân</h2><div class="grid grid-2"><div class="field"><label>Họ và tên</label><input class="input" v-model="form.fullName"></div><div class="field"><label>Email</label><input class="input" v-model="form.email"></div><div class="field"><label>Tên đăng nhập</label><input class="input" v-model="form.username"></div><div class="field"><label>Số điện thoại</label><input class="input" v-model="form.phone"></div></div><div class="toolbar" style="justify-content:flex-end;margin-top:16px"><button class="btn" @click="load">Làm mới</button><button class="btn primary" @click="save">Lưu thay đổi</button></div><h2 class="section-title" style="margin-top:28px">Đổi mật khẩu</h2><div class="grid grid-3"><div class="field"><label>Mật khẩu hiện tại</label><input class="input" type="password" v-model="pass.currentPassword"></div><div class="field"><label>Mật khẩu mới</label><input class="input" type="password" v-model="pass.newPassword"></div><div class="field"><label>Xác nhận</label><input class="input" type="password" v-model="pass.confirmPassword"></div></div><div class="toolbar" style="justify-content:flex-end;margin-top:16px"><button class="btn primary" @click="changePassword">Cập nhật mật khẩu</button></div></section></div></div></template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {authApi,getErrorMessage,getUser} from '../services/api'
const profile=ref(getUser()), error=ref(''), success=ref('')
const form=reactive({fullName:'',email:'',username:'',phone:''}); const pass=reactive({currentPassword:'',newPassword:'',confirmPassword:''})
const initials=computed(()=>String(profile.value.fullName||profile.value.email||'TT').split(' ').map(x=>x[0]).join('').slice(-2).toUpperCase())
function fill(p){Object.assign(form,{fullName:p.fullName||'',email:p.email||'',username:p.username||'',phone:p.phone||''})}
async function load(){try{const {data}=await authApi.profile();profile.value=data;fill(data);localStorage.setItem('librarian_user',JSON.stringify(data))}catch(e){error.value=getErrorMessage(e,'Không tải được hồ sơ.')}}
async function save(){try{await authApi.updateProfile(form);success.value='Cập nhật hồ sơ thành công.';await load()}catch(e){error.value=getErrorMessage(e,'Cập nhật hồ sơ thất bại.')}}
async function changePassword(){if(pass.newPassword!==pass.confirmPassword){error.value='Mật khẩu xác nhận không khớp.';return}try{await authApi.changePassword(pass);success.value='Đổi mật khẩu thành công.';Object.assign(pass,{currentPassword:'',newPassword:'',confirmPassword:''})}catch(e){error.value=getErrorMessage(e,'Đổi mật khẩu thất bại.')}}
onMounted(()=>{fill(profile.value);load()})
</script>
