<template><div>
  <div class="page-head"><div><h1>Bạn đọc</h1><p>Quản lý hồ sơ độc giả, thẻ thư viện và trạng thái sử dụng</p></div><button class="btn primary" @click="openCreate"><i class="mdi mdi-plus"></i>Thêm bạn đọc</button></div>
  <div v-if="error" class="alert error">{{ error }}</div><div v-if="success" class="alert success">{{ success }}</div>
  <div class="grid grid-4"><div class="card stat"><div class="stat-icon blue"><i class="mdi mdi-account-group"></i></div><div><div class="stat-label">Tổng bạn đọc</div><div class="stat-value">{{ readers.length }}</div></div></div><div class="card stat"><div class="stat-icon green"><i class="mdi mdi-card-account-details"></i></div><div><div class="stat-label">Thẻ hợp lệ</div><div class="stat-value">{{ validCards }}</div></div></div><div class="card stat"><div class="stat-icon orange"><i class="mdi mdi-lock-outline"></i></div><div><div class="stat-label">Tạm khóa</div><div class="stat-value">{{ locked }}</div></div></div><div class="card stat"><div class="stat-icon red"><i class="mdi mdi-calendar-alert"></i></div><div><div class="stat-label">Hết hạn thẻ</div><div class="stat-value">{{ expired }}</div></div></div></div>
  <section class="card pad" style="margin-top:16px"><div class="toolbar"><div class="field"><label>Tìm kiếm</label><input class="input" v-model="q" @keyup.enter="load" placeholder="Tên, mã độc giả, mã thẻ, email, SĐT" /></div><button class="btn primary" @click="load">Lọc</button><button class="btn" @click="q='';load()">Đặt lại</button></div></section>
  <div class="split" style="margin-top:16px">
    <section class="card pad"><h2 class="section-title">Danh sách bạn đọc</h2><div class="table-wrap"><table><thead><tr><th>Mã ĐG</th><th>Họ tên</th><th>Email / SĐT</th><th>Thẻ thư viện</th><th>Hết hạn</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><tr v-for="r in readers" :key="r.id"><td>{{r.readerCode}}</td><td><b>{{r.fullName}}</b><br><small>{{r.memberType}}</small></td><td>{{r.email}}<br><small>{{r.phone||'-'}}</small></td><td>{{r.cardNumber||'-'}}</td><td>{{formatDate(r.cardExpiredAt)}}</td><td><span class="badge" :class="isActive(r)?'green':'red'">{{isActive(r)?'Hoạt động':'Tạm khóa'}}</span></td><td class="actions"><button class="mini" @click="select(r)">Xem</button><button class="mini" @click="edit(r)">Sửa</button><button class="mini success" @click="renewCard(r)">Gia hạn</button><button v-if="isActive(r)" class="mini danger" @click="lock(r)">Khóa</button><button v-else class="mini success" @click="unlock(r)">Mở</button></td></tr><tr v-if="!readers.length"><td colspan="7" class="empty">Chưa có bạn đọc. Dữ liệu sẽ có khi Admin thêm hoặc User đăng ký.</td></tr></tbody></table></div></section>
    <section class="card pad"><h2 class="section-title">Thông tin bạn đọc</h2><div v-if="selected" class="info-list"><div class="info-row"><span>Họ tên</span><b>{{selected.fullName}}</b></div><div class="info-row"><span>Mã độc giả</span><b>{{selected.readerCode}}</b></div><div class="info-row"><span>Email</span><b>{{selected.email}}</b></div><div class="info-row"><span>SĐT</span><b>{{selected.phone||'-'}}</b></div><div class="info-row"><span>Mã thẻ</span><b>{{selected.cardNumber||'-'}}</b></div><div class="info-row"><span>Ngày cấp</span><b>{{formatDate(selected.cardIssuedAt)}}</b></div><div class="info-row"><span>Ngày hết hạn</span><b>{{formatDate(selected.cardExpiredAt)}}</b></div><div class="info-row"><span>Giới hạn mượn</span><b>{{selected.borrowLimit||0}} sách</b></div></div><div v-else class="empty">Chọn một bạn đọc để xem thông tin.</div></section>
  </div>
  <section v-if="showForm" class="card pad" style="margin-top:16px"><h2 class="section-title">{{ form.id ? 'Cập nhật bạn đọc' : 'Thêm bạn đọc' }}</h2><div class="grid grid-3"><div class="field"><label>Họ tên</label><input class="input" v-model="form.fullName"></div><div class="field"><label>Email</label><input class="input" v-model="form.email"></div><div class="field"><label>SĐT</label><input class="input" v-model="form.phone"></div><div class="field"><label>Giới tính</label><select class="select" v-model="form.gender"><option value="">Không chọn</option><option>Nam</option><option>Nữ</option></select></div><div class="field"><label>Loại độc giả</label><input class="input" v-model="form.memberType"></div><div class="field"><label>Trạng thái</label><select class="select" v-model.number="form.status"><option :value="1">Hoạt động</option><option :value="2">Tạm khóa</option></select></div></div><div class="field" style="margin-top:12px"><label>Địa chỉ</label><input class="input" v-model="form.address"></div><div class="toolbar" style="justify-content:flex-end;margin-top:14px"><button class="btn" @click="showForm=false">Hủy</button><button class="btn primary" @click="save">Lưu</button></div></section>
</div></template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {identityApi,dataOf,getErrorMessage,formatDate} from '../services/api'
const readers=ref([]), selected=ref(null), q=ref(''), error=ref(''), success=ref(''), showForm=ref(false)
const form=reactive({id:null,fullName:'',email:'',phone:'',gender:'',address:'',memberType:'Thành viên',status:1})
const validCards=computed(()=>readers.value.filter(r=>r.hasValidCard).length), locked=computed(()=>readers.value.filter(r=>!isActive(r)).length), expired=computed(()=>readers.value.filter(r=>r.cardExpiredAt&&new Date(r.cardExpiredAt)<new Date()).length)
function isActive(r){return Number(r.status)===1||r.status==='Active'}
function reset(){Object.assign(form,{id:null,fullName:'',email:'',phone:'',gender:'',address:'',memberType:'Thành viên',status:1})}
function openCreate(){reset();showForm.value=true} function edit(r){Object.assign(form,{id:r.id,fullName:r.fullName,email:r.email,phone:r.phone,gender:r.gender||'',address:r.address||'',memberType:r.memberType||'Thành viên',status:Number(r.status)||1});showForm.value=true} function select(r){selected.value=r}
async function load(){error.value='';try{readers.value=dataOf(await identityApi.readers({q:q.value||undefined})); if(selected.value){selected.value=readers.value.find(r=>r.id===selected.value.id)||null}}catch(e){error.value=getErrorMessage(e,'Không tải được bạn đọc.')}}
async function save(){error.value='';success.value='';try{const payload={...form}; if(form.id) await identityApi.updateReader(form.id,payload); else await identityApi.createReader(payload); success.value='Lưu bạn đọc thành công.';showForm.value=false;await load()}catch(e){error.value=getErrorMessage(e,'Lưu bạn đọc thất bại.')}}
async function renewCard(r){try{await identityApi.renewReaderCard(r.id,{extendMonths:12});success.value='Gia hạn thẻ thành công.';await load()}catch(e){error.value=getErrorMessage(e,'Gia hạn thẻ thất bại.')}}
async function lock(r){if(!confirm('Khóa thẻ của bạn đọc này?'))return;try{await identityApi.lockReaderCard(r.id,{reason:'Khóa bởi thủ thư'});success.value='Đã khóa thẻ.';await load()}catch(e){error.value=getErrorMessage(e,'Khóa thẻ thất bại.')}}
async function unlock(r){try{await identityApi.unlockReaderCard(r.id);success.value='Đã mở khóa thẻ.';await load()}catch(e){error.value=getErrorMessage(e,'Mở khóa thẻ thất bại.')}}
onMounted(load)
</script>
