<template><div><div class="page-head"><div><h1>Lịch sử mượn trả</h1><p>Theo dõi toàn bộ giao dịch mượn, trả, gia hạn và thu phí</p></div><button class="btn" @click="exportCsv"><i class="mdi mdi-file-export-outline"></i>Xuất CSV</button></div><div v-if="error" class="alert error">{{error}}</div><div class="grid grid-4"><div class="card stat"><div class="stat-icon blue"><i class="mdi mdi-file-document-multiple"></i></div><div><div class="stat-label">Tổng giao dịch</div><div class="stat-value">{{tickets.length}}</div></div></div><div class="card stat"><div class="stat-icon orange"><i class="mdi mdi-book-open"></i></div><div><div class="stat-label">Đang mượn</div><div class="stat-value">{{borrowing}}</div></div></div><div class="card stat"><div class="stat-icon green"><i class="mdi mdi-check-circle"></i></div><div><div class="stat-label">Đã trả</div><div class="stat-value">{{returned}}</div></div></div><div class="card stat"><div class="stat-icon red"><i class="mdi mdi-clock-alert"></i></div><div><div class="stat-label">Quá hạn đã xử lý</div><div class="stat-value">{{overdue}}</div></div></div></div><section class="card pad" style="margin-top:16px"><div class="toolbar"><div class="field"><label>Tìm kiếm</label><input class="input" v-model="q" placeholder="Mã phiếu, bạn đọc, sách"></div><div class="field"><label>Trạng thái</label><select class="select" v-model="status"><option value="">Tất cả</option><option value="1">Đang mượn</option><option value="2">Đã trả</option><option value="3">Quá hạn</option></select></div></div></section><div class="split" style="margin-top:16px"><section class="card pad"><h2 class="section-title">Danh sách lịch sử mượn trả</h2><div class="table-wrap"><table><thead><tr><th>Mã phiếu</th><th>Độc giả</th><th>Sách</th><th>Ngày mượn</th><th>Hạn trả</th><th>Ngày trả</th><th>Trạng thái</th><th>Phí</th></tr></thead><tbody><tr v-for="t in filtered" :key="t.id"><td>{{t.ticketCode}}</td><td>{{t.readerName}}<br><small>{{t.readerCode}}</small></td><td>{{(t.items||[]).map(i=>i.bookTitle).join(', ')}}</td><td>{{formatDate(t.borrowDate)}}</td><td>{{formatDate(t.dueDate)}}</td><td>{{formatDate(t.returnDate)}}</td><td><span class="badge" :class="badgeClass(t.status)">{{enumText(t.status,statusMaps.ticket)}}</span></td><td>{{formatMoney((t.items||[]).reduce((s,i)=>s+Number(i.fineAmount||0),0))}}</td></tr><tr v-if="!filtered.length"><td colspan="8" class="empty">Không có giao dịch.</td></tr></tbody></table></div></section><section class="card pad"><h2 class="section-title">Hoạt động gần đây</h2><div v-for="h in logs.slice(0,12)" :key="h.id" class="info-row"><span>{{h.action}}<br><small>{{h.description}}</small></span><b>{{formatDateTime(h.createdAt)}}</b></div><div v-if="!logs.length" class="empty">Chưa có nhật ký nghiệp vụ.</div></section></div></div></template>
<script setup>
import {computed,onMounted,ref} from 'vue'
import {circulationApi,dataOf,getErrorMessage,formatDate,formatDateTime,formatMoney,enumText,statusMaps} from '../services/api'
const tickets=ref([]),logs=ref([]),q=ref(''),status=ref(''),error=ref('')
const borrowing=computed(()=>tickets.value.filter(t=>Number(t.status)===1).length),returned=computed(()=>tickets.value.filter(t=>Number(t.status)===2).length),overdue=computed(()=>tickets.value.filter(t=>Number(t.status)===3).length)
const filtered=computed(()=>tickets.value.filter(t=>(!status.value||String(t.status)===status.value)&&(!q.value||[t.ticketCode,t.readerName,t.readerCode,...(t.items||[]).map(i=>i.bookTitle)].join(' ').toLowerCase().includes(q.value.toLowerCase()))))
function badgeClass(s){return Number(s)===2?'green':Number(s)===3?'red':'blue'}
function exportCsv(){const rows=[['Mã phiếu','Độc giả','Ngày mượn','Hạn trả','Ngày trả','Trạng thái'],...filtered.value.map(t=>[t.ticketCode,t.readerName,formatDate(t.borrowDate),formatDate(t.dueDate),formatDate(t.returnDate),enumText(t.status,statusMaps.ticket)])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lich-su-muon-tra.csv';a.click()}
onMounted(async()=>{try{const [t,h]=await Promise.all([circulationApi.tickets(),circulationApi.history()]);tickets.value=dataOf(t);logs.value=dataOf(h)}catch(e){error.value=getErrorMessage(e,'Không tải được lịch sử.')}})
</script>
