<template><div>
  <div class="page-head"><div><h1>Sách quá hạn</h1><p>Theo dõi phiếu quá hạn, nhắc trả sách và chuyển xử lý phí phạt</p></div><button class="btn" @click="exportCsv"><i class="mdi mdi-file-export-outline"></i>Xuất CSV</button></div>
  <div v-if="error" class="alert error">{{error}}</div>
  <div class="grid grid-4"><div class="card stat"><div class="stat-icon blue"><i class="mdi mdi-file-clock"></i></div><div><div class="stat-label">Phiếu quá hạn</div><div class="stat-value">{{overdue.length}}</div></div></div><div class="card stat"><div class="stat-icon green"><i class="mdi mdi-account-alert"></i></div><div><div class="stat-label">Độc giả quá hạn</div><div class="stat-value">{{readerCount}}</div></div></div><div class="card stat"><div class="stat-icon orange"><i class="mdi mdi-cash"></i></div><div><div class="stat-label">Phạt tạm tính</div><div class="stat-value">{{formatMoney(totalExpected)}}</div></div></div><div class="card stat"><div class="stat-icon red"><i class="mdi mdi-alert-octagon"></i></div><div><div class="stat-label">Nghiêm trọng</div><div class="stat-value">{{critical}}</div></div></div></div>
  <section class="card pad" style="margin-top:16px"><div class="toolbar"><div class="field"><label>Tìm kiếm</label><input class="input" v-model="q" placeholder="Tên độc giả, mã phiếu, mã thẻ"></div><div class="field"><label>Số ngày quá hạn</label><select class="select" v-model="range"><option value="">Tất cả</option><option value="3">Trên 3 ngày</option><option value="7">Trên 7 ngày</option><option value="15">Trên 15 ngày</option></select></div><button class="btn primary">Lọc</button></div></section>
  <div class="split" style="margin-top:16px"><section class="card pad"><h2 class="section-title">Danh sách quá hạn</h2><div class="table-wrap"><table><thead><tr><th>Mã phiếu</th><th>Độc giả</th><th>Sách</th><th>Hạn trả</th><th>Quá hạn</th><th>Phí phạt</th><th>Thao tác</th></tr></thead><tbody><tr v-for="t in filtered" :key="t.id"><td>{{t.ticketCode}}</td><td>{{t.readerName}}<br><small>{{t.readerCode}}</small></td><td>{{(t.items||[]).map(i=>i.bookTitle).join(', ')}}</td><td>{{formatDate(t.dueDate)}}</td><td><span class="badge red">{{overdueDays(t)}} ngày</span></td><td>{{formatMoney(expectedFine(t))}}</td><td><button class="mini" @click="select=t">Xem</button></td></tr><tr v-if="!filtered.length"><td colspan="7" class="empty">Không có sách quá hạn.</td></tr></tbody></table></div></section><section class="card pad"><h2 class="section-title">Chi tiết nhắc nhở</h2><div v-if="select" class="info-list"><div class="info-row"><span>Mã phiếu</span><b>{{select.ticketCode}}</b></div><div class="info-row"><span>Độc giả</span><b>{{select.readerName}}</b></div><div class="info-row"><span>Quá hạn</span><b>{{overdueDays(select)}} ngày</b></div><div class="info-row"><span>Phí tạm tính</span><b>{{formatMoney(expectedFine(select))}}</b></div><button class="btn primary" @click="message='Đã ghi nhận nhắc trả sách cho '+select.readerName">Gửi nhắc nhở</button><div v-if="message" class="alert success" style="margin-top:12px">{{message}}</div></div><div v-else class="empty">Chọn phiếu để xem chi tiết.</div></section></div>
</div></template>
<script setup>
import {computed,onMounted,ref} from 'vue'
import {circulationApi,dataOf,getErrorMessage,formatDate,formatMoney} from '../services/api'
const overdue=ref([]),q=ref(''),range=ref(''),error=ref(''),select=ref(null),message=ref(''); const finePerDay=2000
function overdueDays(t){return Math.max(0,Math.floor((new Date()-new Date(t.dueDate))/86400000))}
function expectedFine(t){return overdueDays(t)*(t.items?.filter(i=>Number(i.itemStatus)!==2).length||1)*finePerDay}
const filtered=computed(()=>overdue.value.filter(t=>{const k=q.value.toLowerCase();const ok=!k||[t.ticketCode,t.readerCode,t.readerName].join(' ').toLowerCase().includes(k);const r=!range.value||overdueDays(t)>=Number(range.value);return ok&&r}))
const readerCount=computed(()=>new Set(overdue.value.map(t=>t.readerCode)).size), totalExpected=computed(()=>filtered.value.reduce((s,t)=>s+expectedFine(t),0)), critical=computed(()=>overdue.value.filter(t=>overdueDays(t)>15).length)
function exportCsv(){const rows=[['Mã phiếu','Độc giả','Hạn trả','Quá hạn','Phí'],...filtered.value.map(t=>[t.ticketCode,t.readerName,formatDate(t.dueDate),overdueDays(t),expectedFine(t)])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sach-qua-han.csv';a.click()}
onMounted(async()=>{try{overdue.value=dataOf(await circulationApi.overdue())}catch(e){error.value=getErrorMessage(e,'Không tải được danh sách quá hạn.')}})
</script>
